apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: builds-registry.ystack.svc.cluster.local/yolean/kafka-keyvalue-nodejs-itest
    context: .
    custom:
      buildCommand: y-build --opt filename=itest.Dockerfile --opt target=watch
      dependencies:
        dockerfile:
          path: ./itest.Dockerfile
    sync:
      manual:
      - src: src/**
        dest: src
        strip: src
deploy:
  kustomize:
    path: ./variant-dev
