kkv:
  target:
    path: ${ON_UPDATE_PATH:/kafka-keyvalue/v1/updates}
    service:
      name: ${TARGET_SERVICE_NAME:}
      port: ${TARGET_SERVICE_PORT:8080}
    static:
      host: ${TARGET_STATIC_HOST:}
      port: ${TARGET_STATIC_PORT:8080}
  dispatcher:
    retry:
      backoff-seconds: ${DISPATCHER_RETRY_BACKOFF_SECONDS:1}
      times: ${DISPATCHER_RETRY_TIMES:5}

mp:
  messaging:
    incoming:
      topic:
        health-readiness-enabled: ${kafka_health_radiness_enabled:false}
        connector:
          smallrye-kafka
        bootstrap:
          servers: ${KAFKA_BOOTSTRAP}
        topic: ${KAFKA_INCOMING_TOPIC}
        enable:
          auto:
            commit: false
        auto:
          offset:
            reset: ${ONUPDATE_AFTER_OFFSET:latest}
        group:
          id: ${KAFKA_GROUP_ID}
        consumer-rebalance-listener:
          name: kkv
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value:
          deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
        interceptor:
          classes: se.yolean.kafka.keyvalue.KafkaPollListener

quarkus:

  http:
    port: ${QUARKUS_HTTP_PORT:8080}

  log:
    category:
      "se.yolean":
        level: DEBUG
      "org.apache.kafka.clients.Metadata":
        level: DEBUG
      "io.fabric8.kubernetes.client":
        level: DEBUG
        min-level: DEBUG
      "io.vertx.core.http":
        level: DEBUG
        min-level: DEBUG

  kafka:
    snappy:
      enabled: true
    devservices:
      # topic-partitions:
      #   operations: 1
      enabled: false

  native:
    native-image-xmx: 4g
    additional-build-args: >-
      --install-exit-handlers,
      --no-fallback
    enable-https-url-handler: true

  ssl:
    native: false
