#!/bin/bash
set -e

echo "------ HOOK START - BUILD -------"
printenv

docker build -t $IMAGE_NAME-plainjava --target runtime-plainjava \
  --build-arg SOURCE_COMMIT=$SOURCE_COMMIT --build-arg SOURCE_BRANCH=$SOURCE_BRANCH --build-arg IMAGE_NAME=$IMAGE_NAME  .

docker build -t $IMAGE_NAME \
  --build-arg SOURCE_COMMIT=$SOURCE_COMMIT --build-arg SOURCE_BRANCH=$SOURCE_BRANCH --build-arg IMAGE_NAME=$IMAGE_NAME .

[ ! -z "$SOURCE_COMMIT" ] && docker push $IMAGE_NAME-plainjava

echo "------ HOOK END   - BUILD -------"
