#!/bin/bash

echo "------ HOOK START - BUILD -------"
printenv

docker build -t $IMAGE_NAME --build-arg SOURCE_COMMIT=$SOURCE_COMMIT --build-arg SOURCE_BRANCH=$SOURCE_BRANCH --build-arg IMAGE_NAME=$IMAGE_NAME .

echo "------ HOOK END   - BUILD -------"
